version: 2
snapshot:
  widths: [375, 768, 1280]
  min-height: 1024
  enable-javascript: true
  percy-css: |
    iframe { display: none; }
    .ad, .advertisement { display: none; }
discovery:
  network-idle-timeout: 750
  wait-for-timeout: 30000
