
services:
  mysql:
    image: mysql:8.0.35
    container_name: hametuha-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    networks:
      - hametuha-network

  wordpress:
    build:
      context: ./docker/wordpress
      dockerfile: Dockerfile
    container_name: hametuha-wordpress
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}
      WORDPRESS_DB_USER: ${MYSQL_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-true}
      # 開発用ドメイン設定
      WP_HOME: ${WP_HOME:-https://hametuha.info}
      WP_SITEURL: ${WP_SITEURL:-https://hametuha.info}
    volumes:
      # WordPressコア（ローカルのwpディレクトリをマウント）
      - ./wp:/var/www/html
      # wp-config.php（個別にマウント）
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./wp-config-local.php:/var/www/html/wp-config-local.php
      # テーマ・プラグイン・アップロード
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./maintenance.php:/var/www/html/wp-content/maintenance.php
      - ./db-error.php:/var/www/html/wp-content/db-error.php
      - ./uploads:/var/www/html/wp-content/uploads
      # WordPressテストスイート
      - ./wp-tests:/var/www/html/wp-tests
      # PHP設定
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      # Composer cache
      - composer_cache:/root/.composer/cache
      # PHP sessions
      - php_sessions:/var/lib/php/sessions
    networks:
      - hametuha-network

  nginx:
    image: nginx:alpine
    container_name: hametuha-nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./wp:/var/www/html
      - ./contents:/var/www/html/contents
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./maintenance.php:/var/www/html/wp-content/maintenance.php
      - ./db-error.php:/var/www/html/wp-content/db-error.php
      - ./uploads:/var/www/html/wp-content/uploads
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
    environment:
      - NGINX_HOST=hametuha.info
    networks:
      - hametuha-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: hametuha-phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER:-wordpress}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
      UPLOAD_LIMIT: 300M
    networks:
      - hametuha-network

  mailpit:
    image: axllent/mailpit
    container_name: hametuha-mailpit
    restart: unless-stopped
    volumes:
      - ./docker/mailpit-data:/data
    ports:
      - "${MAILPIT_UI_PORT:-8026}:8025"
      - "${MAILPIT_SMTP_PORT:-1026}:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - hametuha-network

volumes:
  mysql_data:
  composer_cache:
  php_sessions:

networks:
  hametuha-network:
    driver: bridge
