<?php

namespace Hametuha\WpApi;


use Hametuha\Model\Anpis;
use Hametuha\Model\Notifications;
use WPametu\API\Rest\WpApi;

/**
 * 安否情報用の
 *
 * @property-read Anpis $anpis
 * @property-read Notifications $notifications
 */
class Anpi extends WpApi {

	protected $models = [
		'anpis'         => Anpis::class,
		'notifications' => Notifications::class,
	];

	protected function get_route() {
		return 'anpi/(?P<post_id>new|\d+)/?';
	}

	protected function get_arguments( $method ) {
		$args = [
			'post_id' => [
				'required'          => true,
				'type'              => 'integer',
				'validate_callback' => function( $id ) {
					if ( ! is_numeric( $id ) ) {
						return false;
					}
					$post = get_post( $id );
					if ( ! $post || 'anpi' === $post->post_type ) {
						return false;
					}
					// 持ち主しか見れない
					return ( get_current_user_id() === (int) $post->post_author ) || current_user_can( 'edit_others_posts' );
				},
			],
		];
		if ( 'POST' === $method ) {
			$args['post_id'] = [
				'type'              => 'string',
				'required'          => true,
				'validate_callback' => function( $id ) {
					return 'new' === $id;
				},
			];
		}
		if ( in_array( $method, [ 'POST', 'PUT' ], true ) ) {
			$args = array_merge( [
				'content' => [
					'type'              => 'string',
					'required'          => true,
					'validate_callback' => function( $var ) {
						return ! empty( $var );
					},
				],
				'title' => [
					'type'              => 'string',
					'default'           => '',
				],
			], $args );
		}
		switch ( $method ) {
			case 'GET':
			case 'PUT':
			case 'DELETE':
				$args['post_id'] = [
				];
				break;
			case 'POST':
		}

		return parent::get_arguments( $method ); // TODO: Change the autogenerated stub
	}

	/**
	 * 安否情報の投稿オブジェクトを配列に変換する
	 *
	 * @param \WP_Post $post
	 * @return array{}
	 */
	protected function post_to_response( $post ) {
		$terms = [];
		$term_objects = get_terms( 'anpi_cat', [ 'hide_empty' => false ] );
		if ( $term_objects && ! is_wp_error( $term_objects ) ) {
			foreach ( $term_objects as $term ) {
				$terms[] = [
					'id'     => $term->term_id,
					'name'   => $term->name,
					'active' => has_term( $term->term_id, 'anpi_cat', $post ),
				];
			}
		}
		return [
			'id'         => $post->ID,
			'type'       => 'anpi',
			'status'     => $post->post_status,
			'title'      => $post->post_title,
			'url'        => get_permalink( $post ),
			'date'       => get_gmt_from_date( $post->post_date, DATE_ISO8601 ),
			'modified'   => get_gmt_from_date( $post->post_modified, DATE_ISO8601 ),
			'categories' => $terms,
			'content'    => $post->post_content,
		];
	}

	public function permission_callback( $request ) {
		return current_user_can( 'read' );
	}
}
