AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket for Hametuha Infrastructure Scripts - One-time Setup'

# =============================================================================
# このテンプレートは一度だけ実行します
# 作成されたS3バケットはインフラストラクチャコードのバージョン管理に使用されます
# =============================================================================

Parameters:
  BucketNamePrefix:
    Type: String
    Default: hametuha-infrastructure
    Description: Prefix for S3 bucket name (will append account ID for uniqueness)

Resources:
  # インフラストラクチャスクリプト用S3バケット
  InfrastructureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketNamePrefix}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled  # バージョニング有効（ロールバック対応）
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90  # 古いバージョンは90日後に削除
      Tags:
        - Key: Purpose
          Value: Infrastructure-Scripts
        - Key: Project
          Value: Hametuha
        - Key: ManagedBy
          Value: CloudFormation

  # S3バケットポリシー（EC2からの読み取り許可）
  InfrastructureBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref InfrastructureBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # EC2インスタンスからの読み取り許可
          - Sid: AllowEC2ReadAccess
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub '${InfrastructureBucket.Arn}/*'
              - !GetAtt InfrastructureBucket.Arn
          # 特定のオブジェクトのパブリック読み取り許可（UserDataスクリプト用）
          - Sid: AllowPublicReadForUserData
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource:
              - !Sub '${InfrastructureBucket.Arn}/userdata/*'
            Condition:
              StringEquals:
                s3:ExistingObjectTag/Public: "true"

Outputs:
  BucketName:
    Description: Name of the infrastructure S3 bucket
    Value: !Ref InfrastructureBucket
    Export:
      Name: hametuha-infrastructure-bucket-name

  BucketArn:
    Description: ARN of the infrastructure S3 bucket
    Value: !GetAtt InfrastructureBucket.Arn
    Export:
      Name: hametuha-infrastructure-bucket-arn

  BucketUrl:
    Description: URL of the infrastructure S3 bucket
    Value: !Sub 'https://${InfrastructureBucket}.s3.${AWS::Region}.amazonaws.com'
    Export:
      Name: hametuha-infrastructure-bucket-url

  BucketRegionalUrl:
    Description: Regional URL of the infrastructure S3 bucket
    Value: !Sub 'https://${InfrastructureBucket}.s3-${AWS::Region}.amazonaws.com'
    Export:
      Name: hametuha-infrastructure-bucket-regional-url

  ScriptsBaseUrl:
    Description: Base URL for UserData scripts
    Value: !Sub 'https://${InfrastructureBucket}.s3.${AWS::Region}.amazonaws.com/userdata'
    Export:
      Name: hametuha-infrastructure-scripts-base-url