<?php

namespace Hametuha\QueryHighJack;


use Hametuha\Model\Ideas;
use WPametu\API\QueryHighJack;

/**
 * アイデアにカスタムクエリを追加する
 *
 * @property-read Ideas $ideas
 */
class IdeasQuery extends QueryHighJack {

	/**
	 * Query vars
	 *
	 * @var array
	 */
	protected $query_var = [ 'idea_type' ];

	protected $models = [
		'ideas' => Ideas::class,
	];

	/**
	 * リライトルール
	 *
	 * @var array
	 */
	protected $rewrites = [
		'ideas/(mine|stock)/page/([0-9]+)/?$' => 'index.php?post_type=ideas&idea_type=$matches[1]&paged=$matches[2]',
		'ideas/(mine|stock)/?$'               => 'index.php?post_type=ideas&idea_type=$matches[1]',
	];

	/**
	 * タイトル変更
	 *
	 * @param string $title
	 * @param string $sep
	 * @param string $sep_location
	 *
	 * @return string
	 */
	public function wp_title( $title, $sep, $sep_location ) {
		switch ( get_query_var( 'idea_type' ) ) {
			case 'mine':
				return __( 'あなたのアイデア', 'hametuha' );
			case 'stock':
				return __( 'ストックしたアイデア', 'hametuha' );
			default:
				return $title;
		}
	}

	/**
	 * action for pre_get_posts
	 *
	 * @param \WP_Query $wp_query
	 * @return void
	 */
	public function pre_get_posts( \WP_Query &$wp_query ) {
		if ( $this->is_valid_query( $wp_query ) ) {
			// キャッシュさせない
			if ( $wp_query->is_main_query() ) {
				nocache_headers();
			}
			// ログインしているユーザーでなければ、このクエリは無効
			if ( ! is_user_logged_in() ) {
				if ( ! $wp_query->is_main_query() ) {
					// メインクエリならリダイレクト
					auth_redirect( home_url( sprintf( 'ideas/%s/', get_query_var( 'idea_type' ) )  ) );
					exit;
				} else {
					// そうでなければ404にする
					$wp_query->set_404();
					$wp_query->set( 'post__in', [ 0 ] );
					return;
				}
			}
			switch ( get_query_var( 'idea_type' ) ) {
				case 'mine':
					$wp_query->set( 'author', get_current_user_id() );
					$wp_query->set( 'post_status', [ 'publish', 'private', 'future' ] );
					break;
				case 'stock':
					$wp_query->set( 'stocked_by', get_current_user_id() );
					break;
			}
		}
	}

	public function posts_join( $join, \WP_Query $wp_query ) {
		$stocked_by = $wp_query->get( 'stocked_by' );
		if ( ! is_numeric( $stocked_by ) ) {
			return $join;
		}
		$join .= ' ' . $this->ideas->get_stock_join( (int) $stocked_by );
		return $join;
	}

	public function posts_where( $where, \WP_Query $wp_query ) {
		return parent::posts_where( $where, $wp_query ); // TODO: Change the autogenerated stub
	}


	/**
	 * クエリがKindleかどうか
	 *
	 * @param \WP_Query $wp_query
	 *
	 * @return bool
	 */
	protected function is_valid_query( \WP_Query $wp_query ) {
		return in_array($wp_query->get( 'idea_type' ), [ 'mine', 'stock' ], true );
	}
}
