name: hametuha
type: wordpress
docroot: wp
php_version: "8.1"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.6"
mysql_version: ""
nodejs_version: "16"

# シンボリックリンクによるマッピング
hooks:
  post-start:
    - exec: composer install
    - exec: |
        # シンボリックリンクを作成
        rm -rf /var/www/html/wp-content/themes/hametuha
        ln -sf /var/www/html/themes/hametuha /var/www/html/wp-content/themes/hametuha
        rm -rf /var/www/html/wp-content/plugins
        ln -sf /var/www/html/plugins /var/www/html/wp-content/plugins
        # Create wp-config.php
        wp config create --dbname=db --dbuser=db --dbpass=db --dbhost=db --force || true
        wp config set WP_DEBUG true --raw
        wp config set SCRIPT_DEBUG true --raw
        wp config set WP_DEBUG_LOG true --raw
        wp config set HAMAIL_DEBUG true --raw
    - exec: wp core install --url=$DDEV_PRIMARY_URL --title="Hametuha" --admin_user=admin --admin_email=admin@example.com --skip-email || true
    - exec: wp theme activate hametuha || true

# Web environment variables
web_environment:
  - WP_HOME=https://hametuha.ddev.site
  - WP_SITEURL=https://hametuha.ddev.site

# Custom commands
commands:
  wordpress:
    service: web
    description: Custom wordpress development commands
    commands:
      theme:
        service: web
        description: Theme development commands
        exec-host: "cd themes/hametuha"
        commands:
          build:
            service: web
            description: Build theme assets
            exec: npm run package
          watch:
            service: web
            description: Watch theme assets
            exec: npm run watch